export enum db {
  DB_DIALECT = 'DB_DIALECT',
  DB_HOST = 'DB_HOST',
  DB_PORT = 'DB_PORT',
  DB_USER = 'DB_USER',
  DB_PASSWORD = 'DB_PASSWORD',
  DB_NAME = 'DB_NAME',
  AUTO_LOAD_ENTITIES = 'AUTO_LOAD_ENTITIES',
  DB_LOGGING = 'DB_LOGGING',
}
