export enum Key {
  SERVER_PORT = 'SERVER_PORT',
  SERVER_HOST = 'SERVER_HOST',
  SERVER_VERSION = 'SERVER_VERSION',
  NODE_ENV = 'NODE_ENV',
  SECRET_KEY = 'SECRET_KEY',
  ACCESS_TOKEN_EXPIRATION = "{ expiresIn: '1h' }",
  REFRESH_TOKEN_EXPIRATION = "{ expiresIn: '1d' }"
}
